x-paths:

  profiles_regex_check_type_rules:
    post:
      description: >-
        Create a regex check type settings rule.
      summary: Create a regex check type settings rule
      tags:
        - Translation quality checks
      operationId: createTQCRegexRule
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '../api_common.yaml#/components/parameters/accountUid'
        - $ref: './tqc_common.yaml#/components/parameters/profileUidPathParameter'
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TQCRegexRuleRequest'

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TQCRegexRuleResponse'

      x-code-samples:
        - lang: curl
          source: |
            curl -X POST -H "Authorization: Bearer $smartlingToken" -H "Content-Type: application/json" -d "$smartlingStringTQCJSON" https://api.smartling.com/translation-quality-api/v2/accounts/$smartlingAccountId/profiles/$smartlingProfileUid/check-types/REGEX_CHECK/settings/rules

  profiles_regex_check_type_rule:
    get:
      description: >-
        Get a regex check type settings rule.
      summary: Get a regex check type settings rule
      tags:
        - Translation quality checks
      operationId: getTQCRegexRule
      produces:
        - application/json
      parameters:
        - $ref: '../api_common.yaml#/components/parameters/accountUid'
        - $ref: './tqc_common.yaml#/components/parameters/profileUidPathParameter'
        - $ref: './tqc_common.yaml#/components/parameters/regexRuleUidPathParameter'

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TQCRegexRuleResponse'

      x-code-samples:
        - lang: curl
          source: |
            curl -X GET -H "Authorization: Bearer $smartlingToken" https://api.smartling.com/translation-quality-api/v2/accounts/$smartlingAccountId/profiles/$smartlingProfileUid/check-types/REGEX_CHECK/settings/rules/$smartlingCheckRuleUid
    put:
      description: >-
        Update a regex check type settings rule.
      summary: Update a regex check type settings rule
      tags:
        - Translation quality checks
      operationId: updateTQCRegexRule
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '../api_common.yaml#/components/parameters/accountUid'
        - $ref: './tqc_common.yaml#/components/parameters/profileUidPathParameter'
        - $ref: './tqc_common.yaml#/components/parameters/regexRuleUidPathParameter'
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TQCRegexRuleRequest'

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TQCRegexRuleResponse'

      x-code-samples:
        - lang: curl
          source: |
            curl -X PUT -H "Authorization: Bearer $smartlingToken" -H "Content-Type: application/json" -d "$smartlingStringTQCJSON" https://api.smartling.com/translation-quality-api/v2/accounts/$smartlingAccountId/profiles/$smartlingProfileUid/check-types/REGEX_CHECK/settings/rules/$smartlingCheckRuleUid
    delete:
      description: >-
        Delete a regex check type settings rule.
      summary: Delete a check type settings rule
      tags:
        - Translation quality checks
      operationId: deleteTQCRegexRule
      produces:
        - application/json
      parameters:
        - $ref: '../api_common.yaml#/components/parameters/accountUid'
        - $ref: './tqc_common.yaml#/components/parameters/profileUidPathParameter'
        - $ref: './tqc_common.yaml#/components/parameters/regexRuleUidPathParameter'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../api_common.yaml#/components/schemas/SuccessResponse'
              examples:
                response:
                  value:
                    response:
                      code: SUCCESS
                      data: null

      x-code-samples:
        - lang: curl
          source: |
            curl -X DELETE -H "Authorization: Bearer $smartlingToken" https://api.smartling.com/translation-quality-api/v2/accounts/$smartlingAccountId/profiles/$smartlingProfileUid/check-types/REGEX_CHECK/settings/rules/$smartlingCheckRuleUid

components:
  schemas:

    TQCRegexRuleRequest:
      allOf:
        - $ref: './tqc_common.yaml#/components/schemas/regexRuleModel'

    TQCRegexRuleResponse:
      type: object
      properties:
        response:
          allOf:
            - $ref: '../api_common.yaml#/components/schemas/SuccessResponse'
            - type: object
              properties:
                data:
                  $ref: './tqc_common.yaml#/components/schemas/regexRuleWithRuleUid'