x-paths:

  setup_webhook:
    post:
      summary: Setup URL for issues webhooks
      description: >-
        This is Smartling API endpoint
        Setup URL for receiving issues webhooks
      tags:
        - Issues Webhooks
      operationId: setupIssuesWebhoook
      parameters:
        - $ref: '../../api_common.yaml#/components/parameters/accountUid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: './commons.yaml#/components/schemas/setupWebhookRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                $ref: './examples.yaml#/components/examples/webhookSettings'
              schema:
                $ref: './commons.yaml#/components/schemas/setupWebhookResponse'
          description: OK
      x-code-samples:
      - lang: curl
        source: >
          curl -X POST -H "Authorization: Bearer $smartlingToken" -H
          "Content-Type: application/json"
          https://api.smartling.com/issues-api/v2/accounts/$smartlingAccountId/webhook
    get:
      summary: Get settings issues webhooks
      description: >-
        This is Smartling API endpoint
        Get settings issues webhooks
      tags:
        - Issues Webhooks
      operationId: getIssuesWebhoookSettings
      parameters:
        - $ref: '../../api_common.yaml#/components/parameters/accountUid'
      responses:
        '200':
          content:
            application/json:
              example:
                $ref: './examples.yaml#/components/examples/webhookSettings'
              schema:
                $ref: './commons.yaml#/components/schemas/setupWebhookResponse'
          description: OK
      x-code-samples:
      - lang: curl
        source: >
          curl -X GET -H "Authorization: Bearer $smartlingToken" -H
          "Content-Type: application/json"
          https://api.smartling.com/issues-api/v2/accounts/$smartlingAccountId/webhook

  receive_webhook:
     post:
       summary: Receive issues webhooks
       description: >-
         API on client side to receive webhooks
       tags:
         - Issues Webhooks
       operationId: receiveIssueCallback
       requestBody:
         content:
           application/json:
             schema:
               oneOf:
                 - $ref: './commons.yaml#/components/schemas/webhooks/issueCreatedRequest'
                 - $ref: './commons.yaml#/components/schemas/webhooks/issueDeletedRequest'
                 - $ref: './commons.yaml#/components/schemas/webhooks/issueAnsweredRequest'
                 - $ref: './commons.yaml#/components/schemas/webhooks/issueSeverityLevelChangedRequest'
                 - $ref: './commons.yaml#/components/schemas/webhooks/issueCommentAdded'
                 - $ref: './commons.yaml#/components/schemas/webhooks/issueWatcherAdded'
         required: true
       responses:
         '200':
           content:
             application/json:
               schema:
                 $ref: './commons.yaml#/components/schemas/receiveWebhookResponse'
           description: OK
       x-code-samples:
       - lang: curl
         source: >
           curl -X GET -H "Authorization: Bearer $smartlingToken" -H
           "Content-Type: application/json"
           https://api.smartling.com/issues-api/v2/accounts/$smartlingAccountId/callback
